import { expect } from "chai";
import { Asset } from "../asset";
import { PublicKey, SecretKey } from "../keypair";
import { PreUtxo, Utxo } from "../utxo";

const sampleAsset = new Asset(1, 3);

// Sample data generated by nargo, see circuit/acir/keypair_acir.txt
const sampleSk = new SecretKey(BigInt(2), BigInt(0));
const samplePk = new PublicKey(
  BigInt("0x6ce1b0827aafa85ddeb49cdaa36306d19a74caa311e13d46d8bc688cdbffffe"),
  BigInt("0x1c122f81a3a14964909ede0ba2a6855fc93faf6fa1a788bf467be7e7a43f80ac"),
  false
);

const sampleRandomness = BigInt(10);

describe("Utxo commitment", () => {
  it(`Should form same UTXO as Noir`, async () => {
    const preUtxo = new PreUtxo(sampleAsset, samplePk, sampleRandomness);
    const utxo = new Utxo(preUtxo);
    console.log(`Utxo commitment: ${utxo.commitment.toString()}`);
    const expectedUtxoCommitment = BigInt(
      "0x2d6c579e6547d5a4c6ff9cab55c183a82024f1c4b6ef12b6d871cfe608b22a0c"
    );
    expect(utxo.commitment === expectedUtxoCommitment);
  });
});
